apiVersion: v1
kind: Namespace
metadata:
  name: otel-demo
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx-space
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
